USE DATABASE NOVAMART_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
TYPE = 'CSV'
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE RAW.NOVAMART_STAGE
FILE_FORMAT = RAW.CSV_FORMAT;

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
    customer_id INTEGER,
    first_name VARCHAR,
    last_name VARCHAR,
    email VARCHAR,
    state VARCHAR,
    created_at DATE
);

CREATE OR REPLACE TABLE RAW.PRODUCTS (
    product_id INTEGER,
    product_name VARCHAR,
    category VARCHAR,
    unit_price NUMBER(10,2)
);

CREATE OR REPLACE TABLE RAW.ORDERS (
    order_id INTEGER,
    customer_id INTEGER,
    order_date DATE,
    status VARCHAR
);

CREATE OR REPLACE TABLE RAW.ORDER_ITEMS (
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    unit_price NUMBER(10,2)
);

CREATE OR REPLACE TABLE RAW.PAYMENTS (
    payment_id INTEGER,
    order_id INTEGER,
    payment_method VARCHAR,
    payment_status VARCHAR,
    amount NUMBER(10,2),
    paid_at TIMESTAMP_NTZ
);