USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER;

GRANT USAGE ON WAREHOUSE COMPUTE_WH
TO ROLE TRANSFORMER;

GRANT USAGE ON DATABASE NOVAMART_DB
TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA NOVAMART_DB.RAW
TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA NOVAMART_DB.STAGING
TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA NOVAMART_DB.INTERMEDIATE
TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA NOVAMART_DB.MARTS
TO ROLE TRANSFORMER;

GRANT SELECT ON ALL TABLES IN SCHEMA NOVAMART_DB.RAW
TO ROLE TRANSFORMER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA NOVAMART_DB.RAW
TO ROLE TRANSFORMER;

GRANT CREATE VIEW, CREATE TABLE
ON SCHEMA NOVAMART_DB.STAGING
TO ROLE TRANSFORMER;

GRANT CREATE VIEW, CREATE TABLE
ON SCHEMA NOVAMART_DB.INTERMEDIATE
TO ROLE TRANSFORMER;

GRANT CREATE VIEW, CREATE TABLE
ON SCHEMA NOVAMART_DB.MARTS
TO ROLE TRANSFORMER;