-- Before running this script, upload the CSV files from /data
-- to the Snowflake internal stage RAW.NOVAMART_STAGE.
COPY INTO RAW.CUSTOMERS
FROM @RAW.NOVAMART_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.PRODUCTS
FROM @RAW.NOVAMART_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.ORDERS
FROM @RAW.NOVAMART_STAGE/orders.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.ORDER_ITEMS
FROM @RAW.NOVAMART_STAGE/order_items.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW.PAYMENTS
FROM @RAW.NOVAMART_STAGE/payments.csv
FILE_FORMAT = (FORMAT_NAME = RAW.CSV_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';